-- =======================================================
-- Schema creation
-- =======================================================
CREATE SCHEMA IF NOT EXISTS auth;

-- =======================================================
-- Table: role
-- =======================================================
CREATE TABLE auth.role (
    id_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- =======================================================
-- Table: user_account
-- =======================================================
CREATE TABLE auth.user_account (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    identity_document VARCHAR(50) NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    phone VARCHAR(30),
    id_role BIGINT NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_identity_document UNIQUE (identity_document),
    CONSTRAINT fk_user_role
        FOREIGN KEY (id_role)
        REFERENCES auth.role (id_role)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- =======================================================
-- Table: credentials
-- =======================================================
CREATE TABLE auth.credentials (
    id_credentials BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user BIGINT NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT fk_credentials_user
        FOREIGN KEY (id_user)
        REFERENCES auth.user_account (id_user)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =======================================================
-- Table: token_session
-- =======================================================
CREATE TABLE auth.token_session (
    id_token_session BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user BIGINT NOT NULL,
    token TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_token_user
        FOREIGN KEY (id_user)
        REFERENCES auth.user_account (id_user)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =======================================================
-- indexes
-- =======================================================
CREATE INDEX IF NOT EXISTS idx_user_account_id_role ON auth.user_account(id_role);
CREATE INDEX IF NOT EXISTS idx_token_session_id_user ON auth.token_session(id_user);
CREATE UNIQUE INDEX IF NOT EXISTS uq_token_session_token ON auth.token_session(token);

-- =======================================================
-- Initial seed data (Roles)
-- =======================================================
INSERT INTO auth.role (name, description) VALUES
('ADMIN', 'System administrator with full access to all modules.'),
('STUDENT', 'User enrolled in training modules.'),
('INSTRUCTOR', 'Trainer responsible for managing and delivering courses.');